server:
  port: 8081
spring:
  application:
    name: config-service
#Apuntar el path a la ruta
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JosueVargasGuia/config-service-data.git
          default-label: Josue
#          search-paths: /config-service-data
#          username:
#          password: