server:
  port: 8081
spring:
  application:
    name: config-service
#Apuntar el path a la ruta
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JosueVargasGuia/config-service-data.git
          default-label: Josue
#          search-paths: /config-service-data
#          username:
#          password:
logging:
  file:
    name: log/${spring.application.name}.log   
  logback:
    rollingpolicy:
      max-file-size: 3MB
      file-name-pattern: log/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
      total-size-cap: 100MB
      clean-history-on-start: true
      max-history: 10